services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: shellton/nabad:latest
    restart: always
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: 3126
    ports:
      - "3126:3126"
